name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: sbt
    - run: sbt 'scalafmtCheckAll; scalafmtSbtCheck'
    - run: sbt '+ clean; + coverage; + test; + coverageReport'
    - uses: paambaati/codeclimate-action@v3.2
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        coverageLocations: |
          ${{github.workspace}}/target/*/coverage-report/cobertura.xml:cobertura
    - run: sbt '++ 2.12.16 -v mimaReportBinaryIssues'
