name: Scala Steward

# This workflow will launch at 9:00 every Monday in JST
on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Scala Steward
    steps:
      - id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.SCALA_STEWARD_APP_ID }}
          private_key: ${{ secrets.SCALA_STEWARD_APP_PRIVATE_KEY }}
      - uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
